config/routes.rb
Rails.application.routes.draw do

  root "games#index"

  get '/secret_numbers', to: 'secret_numbers#new'

  resources :secret_numbers, :only => [:new, :show]

  get '/rock_paper_scissors', to: 'rock_paper_scissors#new'

  resources :rock_paper_scissors, :only => [:new, :show]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
	def index
	end
end

app/controllers/rock_paper_scissors_controller.rb
class RockPaperScissorsController < ApplicationController

	def new
	end

	def show
		player_guess = params[:id]
		computer_guess=[0,1,2].sample
		puts "guess = #{player_guess}, #{computer_guess}"
		@result = compute_winner(player_guess.to_i, computer_guess.to_i)
	end

	private
		def compute_winner(pg,cg)
			puts "player guess is #{pg}, computer guess is #{cg}"
			if pg == cg
				output = 'draw'
			elsif pg == 0
				if cg == 1
					output = "loses"
				else
					output = "wins"
				end
			elsif pg == 1
				if cg == 0
					output = "wins"
				else
					output = "loses"
				end
			elsif pg == 2
				if cg == 1
					output = "wins"
				else
					output = "loses"
				end
			end
			puts "hi my name is " + output
			output
		end
end

app/controllers/secret_numbers_controller.rb
class SecretNumbersController < ApplicationController
	def new
	end

	def show
		# Get a random number
		@secret_number = rand(5)+1

		# get the user chose number from params
		@chosen_number = params[:id].to_i
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/index.html.erb
<h1>Welcome to the Game Centre!</h1>

<p>Choose a game below to get started:</p>

<ul class="games">
	<li>
	<%= link_to image_tag("games/secret-number.jpg"), new_secret_number_path %>
		<h3>Secret Number</h3>
	</li>
	<li>
		<%=image_tag("games/rock-paper-scissors.jpg")%>
		<h3>Rock Paper Scissors</h3>
	</li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GameCentre</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/rock_paper_scissors/new.html.erb
<h1>Welcome to Rock Paper Scissors!</h1>

<p>To play this game, select Rock, Paper or Scissors. You know the rest...</p>

<h2>Pick attack:</h2>

<%= link_to image_tag("rock_paper_scissors/rock.jpeg"), rock_paper_scissor_path(0) %>
<%= link_to image_tag("rock_paper_scissors/paper.jpeg"), rock_paper_scissor_path(1) %>
<%= link_to image_tag("rock_paper_scissors/scissors.jpeg"), rock_paper_scissor_path(2) %>

app/views/rock_paper_scissors/show.html.erb
<% if @result == "wins" %>
	<h1>CONGRATS! YOU WON!</h1>
	<h3>Computer guess: <%=@computer_guess%> Your guess: <%=@player_guess%></h3>
	<p><%= image_tag 'games/cat-wins.gif' %></p>
<% elsif @result == "draw" %>
	<h1>You drew</h1>
<% else %>
	<h1>Sorry, you lose...</h1>
	<p><%= image_tag 'games/loser.gif' %></p>
	<p><%= puts @player_guess.class, @computer_guess %></p>
<% end %>

<p>
	<h3><%= link_to "PLAY AGAIN", new_rock_paper_scissor_path %></h3>
</p>

app/views/secret_numbers/new.html.erb
<h1>Welcome to Secret Number!</h1>

<p>To play this game, all you have to do is guess a number. If you guess the <em>Secret Number</em> you win!</p>

<h2>Pick a number:</h2>

<% (1..5).each do |number| %>
	<%= link_to image_tag("secret_numbers/#{number}.jpeg"), secret_number_path(number) %>
<% end %>

app/views/secret_numbers/show.html.erb
<% if @secret_number == @chosen_number %>
	<h1>CONGRATS! YOU WON!</h1>
	<h3>The secret number was <%=@secret_number%></h3>
	<p><%= image_tag 'games/cat-wins.gif' %></p>
<% else %>
	<h1>Sorry, you lose...</h1>
	<h3>The secret number was <%=@secret_number%></h3>
	<p><%= image_tag 'games/loser.gif' %></p>
<% end %>

<p>
	<h3><%= link_to "PLAY AGAIN", new_secret_number_path %></h3>
</p>